services:
  - type: web
    name: dharmabot
    env: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: gunicorn dharmabot.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DB_NAME
        value: DharmaAIProject
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: 1234
      - key: DB_HOST
        value: your-postgres-host.render.com  
      - key: DB_PORT
        value: 5432
