services:
  - type: web
    name: dharmabot
    env: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: gunicorn dharmabot.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DB_NAME
        value: cluster0
      - key: DB_USER
        value: anjali 
      - key: DB_PASSWORD
        value: anjali@123 
      - key: DB_HOST
        value: cluster0.6w2yp.mongodb.net  
      - key: MONGO_URI
        value: mongodb+srv://anjali:anjali%40123@cluster0.6w2yp.mongodb.net/mydatabase?retryWrites=true&w=majority  
