services:
  - type: web
    name: dharmabot
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dharmabot.wsgi:application --bind 0.0.0.0:8000"
    plan: free
